[theme]
base = "light"
# You can customize the theme here if desired
# primaryColor = "#F63366"
# backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#F0F2F6"
# textColor = "#262730"
# font = "sans serif"
